/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "secondary-fixed": "#ffddb2",
              "surface-tint": "#5f5e5e",
              "surface": "#fcf9f8",
              "on-tertiary-fixed-variant": "#484741",
              "tertiary-fixed": "#e6e2da",
              "on-background": "#1c1b1b",
              "on-primary-fixed-variant": "#474646",
              "surface-container": "#f0edec",
              "inverse-on-surface": "#f3f0ef",
              "error": "#ba1a1a",
              "tertiary": "#000000",
              "paper-bg": "#F2EEE6",
              "surface-variant": "#e5e2e1",
              "primary": "#000000",
              "on-secondary": "#ffffff",
              "error-container": "#ffdad6",
              "on-primary-container": "#858383",
              "on-error": "#ffffff",
              "tertiary-container": "#1c1c17",
              "surface-container-high": "#ebe7e7",
              "on-tertiary": "#ffffff",
              "muted-brass": "rgba(181, 138, 75, 0.15)",
              "secondary-fixed-dim": "#efbe7a",
              "tertiary-fixed-dim": "#c9c6bf",
              "inverse-surface": "#313030",
              "on-tertiary-container": "#86847d",
              "on-secondary-fixed": "#291800",
              "on-surface": "#1c1b1b",
              "on-error-container": "#93000a",
              "secondary": "#7c571d",
              "on-primary-fixed": "#1c1b1b",
              "primary-container": "#1c1b1b",
              "ink-black": "#0E0E0E",
              "on-primary": "#ffffff",
              "on-secondary-fixed-variant": "#614005",
              "surface-container-low": "#f6f3f2",
              "surface-container-lowest": "#ffffff",
              "background": "#fcf9f8",
              "surface-dim": "#dcd9d9",
              "inverse-primary": "#c9c6c5",
              "primary-fixed-dim": "#c9c6c5",
              "on-secondary-container": "#79551b",
              "surface-bright": "#fcf9f8",
              "on-surface-variant": "#444748",
              "outline-variant": "#c4c7c7",
              "on-tertiary-fixed": "#1c1c17",
              "surface-container-highest": "#e5e2e1",
              "secondary-container": "#fecc86",
              "primary-fixed": "#e5e2e1",
              "brass-gold": "#B58A4B",
              "outline": "#747878"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "margin-mobile": "20px",
              "gutter": "24px",
              "container-max": "1280px",
              "margin-desktop": "64px",
              "section-gap": "120px"
          },
          "fontFamily": {
              "body-md": ["\"Source Serif 4\""],
              "headline-xl-mobile": ["Chivo"],
              "headline-lg": ["Chivo"],
              "label-sm": ["Space Mono"],
              "body-lg": ["\"Source Serif 4\""],
              "display-lg": ["Chivo"],
              "eyebrow": ["Space Mono"],
              "headline-xl": ["Chivo"]
          },
          "fontSize": {
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "headline-xl-mobile": ["36px", {"lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-lg": ["32px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "400"}],
              "body-lg": ["20px", {"lineHeight": "32px", "fontWeight": "400"}],
              "display-lg": ["80px", {"lineHeight": "72px", "letterSpacing": "-0.04em", "fontWeight": "800"}],
              "eyebrow": ["10px", {"lineHeight": "12px", "letterSpacing": "0.15em", "fontWeight": "700"}],
              "headline-xl": ["48px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
          }
      }
  },
  plugins: [],
}
